# Generated by Django 5.0.7 on 2024-08-03 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departmentheads')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicGoals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('keyArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.keyareas')),
                ('leads', models.ManyToManyField(to='leads.lead')),
                ('members', models.ManyToManyField(to='departments.departmentheads')),
            ],
            options={
                'unique_together': {('goal_id',)},
            },
        ),
        migrations.CreateModel(
            name='StrategicObjectives',
            fields=[
                ('objective_id', models.AutoField(primary_key=True, serialize=False)),
                ('strategicObjectives', models.TextField(default='')),
                ('kpi', models.TextField(default='')),
                ('target', models.TextField(default='')),
                ('evalMeasures', models.TextField(default='')),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.strategicgoals')),
            ],
        ),
    ]
