# Generated by Django 5.0.3 on 2024-08-04 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlans',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('actionPlan', models.TextField(default='')),
                ('kpi', models.TextField(default='')),
                ('targetOutput', models.TextField(default='')),
                ('personResponsible', models.TextField(default='')),
                ('budget', models.FloatField()),
                ('timeFrame', models.DateField(default=django.utils.timezone.now)),
                ('objective_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.strategicobjectives')),
            ],
        ),
    ]
