# Generated by Django 5.0.3 on 2024-08-04 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_actionplans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionplans',
            name='timeFrame',
        ),
        migrations.AddField(
            model_name='actionplans',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='actionplans',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
